"""
(C) Copyright Daan Camps, Mercy Amankwah, E. Wes Bethel, Talita Perciano and
              Roel Van Beeumen

QPIXL - Quantum Pixel Library (Qiskit Python Implementation)
PGM (Portable Grayscale Map) file I/O utilities
"""

import numpy as np
from typing import Tuple
import math


def nextpow2(n: int) -> int:
    """Returns the next power of 2 greater than or equal to n."""
    if n <= 0:
        return 1
    return 2 ** math.ceil(math.log2(n))


def read_pgma(file_name: str, zero_pad: int = 0) -> Tuple[np.ndarray, int, int, int]:
    """
    Read portable grayscale map (PGM) in ASCII format from file.
    
    Args:
        file_name: Path to the PGM file
        zero_pad: Determines how data is padded to the next power of 2
                  0 - no zero padding (default)
                  1 - image is embedded in a 2^n x 2^m image
                  2 - vector is zero padded to the next power of 2
    
    Returns:
        Tuple containing (data, nrows, ncols, maxval)
    """
    try:
        with open(file_name, 'r') as f:
            # Read first line: version
            version = f.readline().strip()
            if version != "P2":
                raise ValueError(f"ERROR -- Version: {version}")
            
            # Read next line, skip if comment
            line = f.readline().strip()
            while line.startswith('#'):
                line = f.readline().strip()
            
            # Parse dimensions
            parts = line.split()
            ncols = int(parts[0])
            nrows = int(parts[1])
            
            # Read maximum pixel value
            maxval = int(f.readline().strip())
            
            # Read all remaining data
            remaining_data = f.read().split()
            
            # Initialize data array based on zero_pad option
            if zero_pad == 0:
                data = np.zeros(nrows * ncols, dtype=float)
                ldm = nrows
            elif zero_pad == 1:
                pow2nrows = nextpow2(nrows)
                pow2ncols = nextpow2(ncols)
                data = np.zeros(pow2nrows * pow2ncols, dtype=float)
                ldm = pow2nrows
            elif zero_pad == 2:
                pow2tot = nextpow2(nrows * ncols)
                data = np.zeros(pow2tot, dtype=float)
                ldm = nrows
            else:
                raise ValueError(f"ERROR -- zeroPad: {zero_pad}")
            
            # Read data in column-major order (matching C++ version)
            idx = 0
            for row in range(nrows):
                for col in range(ncols):
                    data[row + col * ldm] = float(remaining_data[idx])
                    idx += 1
            
            return data, nrows, ncols, maxval
            
    except FileNotFoundError:
        raise FileNotFoundError(f"ERROR -- failed to open {file_name}")


def write_pgma(file_name: str, data: np.ndarray, nrows: int, ncols: int, 
               maxval: int, zero_pad: int = 0) -> None:
    """
    Write grayscale data to a portable grayscale map (PGM) file in ASCII format.
    
    Args:
        file_name: Output file path
        data: numpy array containing image data
        nrows: number of rows in the image
        ncols: number of columns in the image
        maxval: maximum pixel value
        zero_pad: type of zero padding (0, 1, or 2)
    """
    try:
        with open(file_name, 'w') as f:
            # Write header
            f.write("P2\n")
            f.write("# Generated by QPIXL Python\n")
            f.write(f"{ncols} {nrows}\n")
            f.write(f"{maxval}\n")
            
            # Determine leading dimension based on zero_pad
            if zero_pad == 0 or zero_pad == 2:
                ldm = nrows
            elif zero_pad == 1:
                ldm = nextpow2(nrows)
            else:
                raise ValueError(f"ERROR -- zeroPad: {zero_pad}")
            
            # Write data
            for row in range(nrows):
                for col in range(ncols):
                    pixel_val = data[row + col * ldm]
                    pixel_val = int(np.ceil(pixel_val))
                    pixel_val = max(0, min(pixel_val, maxval))
                    f.write(f"{pixel_val} ")
                f.write("\n")
                
    except IOError:
        raise IOError(f"ERROR -- failed to open {file_name}")


# Utility functions for Qiskit quantum image processing
def pgm_to_quantum_state(file_name: str, zero_pad: int = 1) -> Tuple[np.ndarray, int, int]:
    """
    Load a PGM image and prepare normalized data for quantum state preparation.
    
    Args:
        file_name: Path to PGM file
        zero_pad: Padding option (use 1 or 2 for quantum processing)
        
    Returns:
        Tuple of (normalized_data, nrows, ncols)
    """
    data, nrows, ncols, maxval = read_pgma(file_name, zero_pad=zero_pad)
    
    # Normalize data to [0, 1]
    normalized_data = data / maxval if maxval > 0 else data
    
    # Normalize to unit vector for quantum state
    norm = np.linalg.norm(normalized_data)
    if norm > 0:
        normalized_data = normalized_data / norm
    
    return normalized_data, nrows, ncols


def quantum_state_to_pgm(file_name: str, quantum_data: np.ndarray, 
                         nrows: int, ncols: int, maxval: int = 255, 
                         zero_pad: int = 1) -> None:
    """
    Convert quantum state amplitudes back to PGM format.
    
    Args:
        file_name: Output file path
        quantum_data: Quantum state amplitudes
        nrows: Number of rows in output image
        ncols: Number of columns in output image
        maxval: Maximum pixel value (default 255)
        zero_pad: Padding option used
    """
    # Convert quantum amplitudes to pixel values
    pixel_data = np.abs(quantum_data) * maxval
    write_pgma(file_name, pixel_data, nrows, ncols, maxval, zero_pad)